version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      - python -m pip install poetry
      - python -m poetry config virtualenvs.create false
      - rm build.py
      - python -m poetry self add "poetry-dynamic-versioning[plugin]"
    post_install:
      - sed -i '/script \= \"build.py\"/d' pyproject.toml
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --with docs

sphinx:
  configuration: docs/conf.py
