version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_checkout:
      - git fetch --unshallow || true
    post_install:
      - python -m pip install uv
      - SKIP_PRE_BUILD=true UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH uv sync --group docs

sphinx:
  configuration: docs/conf.py
