version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_checkout:
      - git fetch --unshallow || true
    post_create_environment:
      - python -m pip install poetry
      - python -m poetry self add "poetry-dynamic-versioning[plugin]"
    post_install:
      - SKIP_PRE_BUILD=true VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --with docs

sphinx:
  configuration: docs/conf.py
