[default]
extend-ignore-identifiers-re = [
    "(?i)mosquitto", # name of https://github.com/eclipse-mosquitto/mosquitto
    "(?i)redirect_resonse_codes", # bug in geventhttpclient, fixed in https://github.com/geventhttpclient/geventhttpclient/pull/244
]

[files]
extend-exclude = [
    "CHANGELOG.md" # generated file
]
