name: Bug
description: Report an error
labels: ["bug"]
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      options:
        - label: I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
          required: true
        - label: I am reporting a bug, not asking a question
          required: true

  - type: markdown
    attributes:
      value: |
        If you just need help with something, then:

         * [Check the documentation](https://docs.locust.io/en/stable/)
         * [Check the FAQ in the wiki](https://github.com/locustio/locust/wiki/FAQ) 
         * [Check the Github Discussions](https://github.com/orgs/locustio/discussions) 
         * Search [Stack Overflow](https://stackoverflow.com/questions/tagged/locust), or [ask there](https://stackoverflow.com/questions/ask) yourself. If you tag your question with `locust` we will see it.
         * Ask on [Locust's slack](https://locustio.slack.com) [(sign up here)](https://communityinviter.com/apps/locustio/locust)

  - type: textarea
    attributes:
      label: Description
      description: What happened, and what did you want/expect to happen?
    validations:
      required: true

  - type: input
    attributes:
      label: Command line
      description: |
        For example: locust -f mylocustfile.py -t 10s --headless
    validations:
      required: true

  - type: textarea
    attributes:
      label: Locustfile contents
      description: Please remove everything that isn't necessary to trigger the issue.
      render: python3
    validations:
      required: true

  - type: input
    attributes:
      label: Python version
    validations:
      required: true

  - type: input
    attributes:
      label: Locust version
    validations:
      required: true

  - type: input
    attributes:
      label: Operating system
    validations:
      required: true
