blank_issues_enabled: false
contact_links:
  - name: FAQ
    url: https://github.com/locustio/locust/wiki/FAQ
    about: Check the FAQ in the wiki
  - name: Question
    url: https://stackoverflow.com/questions/tagged/locust
    about: Ask questions and look for answers on StackOverflow
  - name: Chat
    url: https://locustio.slack.com
    about: Talk to other Locust users on Slack
